negaciones = [
    "No",
    "Nunca",
    "Jamás",
    "Nada",
    "Nadie",
    "Ningún",
    "Tampoco",
    "Ni",
    "Ni siquiera",
    "De ningún modo",
    "De ninguna manera",
    "En absoluto",
    "Para nada",
    "Sin embargo",
    "Pero no",
    "Sin",
    "Sino",
    "A excepción de",
    "Excepto",
    "Salvo"
]